### ISSUE TITLE
Delay using 'gs' on visual selection

### ISSUE THREAD

**Issue by cmcginty** [christoomey/vim-sort-motion#4]
Could just be my config, but when I select text and type `gs` there is a delay before the sort starts. It seems that the command is waiting for more input. Is this a bug or possible there are extra options you can add after `gs` that change the output?

**Comment by christoomey** [comment]
Hi @cmcginty, typically if you have a delay it means there is another, longer mapping that starts with current sequence. Von waits for a specified time to see if you complete the longer sequence, or stick with the shorter.

You can check this by running `nmap gs`. If you see any other mapping a than the sort motion mapping then you've found the culprit.

**Comment by cmcginty** [comment]
The issues is in visual mode. This is that I have for `vmap`:
```
v  gs            <Plug>SortMotionVisual
   gss           <Plug>SortLines
```

It looks like th `gss` mapping applies to all modes, but should only be command.

**Comment by christoomey** [comment]
Hi @cmcginty, sorry, I misunderstood the initial question. I see it now. Turns out I must have never really tested the visual mapping thoroughly. I'll poke around and I expect I can sort this out. In the mean time, your best option is to try to use line based normal mode sorting, for example `gs2j` to sort down two lines. Sorry I don't have a better solution right now.

**Comment by cmcginty** [comment]
I don't know what `gss` is supposed to do, but you can remove the visual mode map by using `nmap` instead of `map`.  `nmap` will just set the mode for normal mode.

**Comment by christoomey** [comment]
Hey Casey, I think you're right, although it looks as though `gss` is
actually fully broken right now. I'd gladly accept a PR that removes it
wholesale if you're interested.
